#!/usr/bin/env python3
"""
Build complete communes prospects list for Piou.
All communes in Suisse romande within ~100km of Arzier (1273).
Categories: VD, GE, FR, NE, JU, VS (all communes)
"""

import openpyxl

# === ALL COMMUNES IN SUISSE ROMANDE ===
# Format: (nom, code_postal, email_general, telephone, site_web)

vaud = [
    ("Aigle", 1860, "", "", "https://www.aigle.ch"),
    ("Avenches", 1580, "", "", "https://www.avenches.ch"),
    ("Ballaigues", 1338, "", "", "https://www.ballaigues.ch"),
    ("Bavois", 1372, "", "", "https://www.bavois.ch"),
    ("Begnins", 1268, "", "", "https://www.begnins.ch"),
    ("Bex", 1880, "", "", "https://www.bex.ch"),
    ("Bière", 1145, "", "", "https://www.biere.ch"),
    ("Bottens", 1041, "", "", "https://www.bottens.ch"),
    ("Bursins", 1183, "", "", "https://www.bursins.ch"),
    ("Bussigny", 1030, "", "", "https://www.bussigny.ch"),
    ("Bussy-Chardonney", 1136, "", "", ""),
    ("Chardonne", 1803, "", "", "https://www.chardonne.ch"),
    ("Chavannes-de-Bogis", 1279, "", "", ""),
    ("Chavannes-des-Bois", 1290, "", "", ""),
    ("Chavornay", 1373, "", "", "https://www.chavornay.ch"),
    ("Cheseaux-Noréaz", 1400, "", "", ""),
    ("Cheseaux-sur-Lausanne", 1033, "", "", "https://www.cheseaux.ch"),
    ("Chigny", 1134, "", "", ""),
    ("Clarmont", 1127, "", "", ""),
    ("Coinsins", 1267, "", "", ""),
    ("Colombier (VD)", 1114, "", "", ""),
    ("Concise", 1426, "", "", "https://www.concise.ch"),
    ("Coppet", 1296, "", "", "https://www.coppet.ch"),
    ("Cossonay", 1304, "", "", "https://www.cossonay.ch"),
    ("Crans (VD)", 1299, "", "", ""),
    ("Crassier", 1263, "", "", ""),
    ("Crissier", 1023, "", "", "https://www.crissier.ch"),
    ("Croy", 1322, "", "", ""),
    ("Cudrefin", 1588, "", "", "https://www.cudrefin.ch"),
    ("Cully", 1096, "", "", ""),
    ("Daillens", 1306, "", "", ""),
    ("Denges", 1026, "", "", ""),
    ("Denens", 1135, "", "", ""),
    ("Démoret", 1415, "", "", ""),
    ("Denizy", 1131, "", "", ""),
    ("Donneloye", 1407, "", "", ""),
    ("Duillier", 1266, "", "", "https://www.duillier.ch"),
    ("Eclépens", 1312, "", "", ""),
    ("Ecoteaux", 1612, "", "", ""),
    ("Ecublens (VD)", 1024, "", "", "https://www.ecublens.ch"),
    ("Epalinges", 1066, "", "", "https://www.epalinges.ch"),
    ("Essertines-sur-Rolle", 1186, "", "", ""),
    ("Eysins", 1262, "", "", ""),
    ("Féchy", 1173, "", "", ""),
    ("Ferreyres", 1313, "", "", ""),
    ("Founex", 1297, "", "", ""),
    ("Genolier", 1272, "", "", "https://www.genolier.ch"),
    ("Gilly", 1182, "", "", ""),
    ("Gimel", 1188, "", "", ""),
    ("Gingins", 1276, "", "", ""),
    ("Givrins", 1271, "", "", ""),
    ("Gland", 1196, "", "", "https://www.gland.ch"),
    ("Gollion", 1124, "", "", ""),
    ("Grancy", 1117, "", "", ""),
    ("Grandcour", 1543, "", "", ""),
    ("Grandson", 1422, "", "", "https://www.grandson.ch"),
    ("Grens", 1274, "", "", ""),
    ("Grimisuat", 1971, "", "", ""), # VS
    ("Granges-près-Marnand", 1523, "", "", ""),
    ("Gryon", 1882, "", "", ""),
    ("Hautemorges", 1141, "", "", ""),
    ("Jongny", 1805, "", "", ""),
    ("Jouxtens-Mézery", 1008, "", "", ""),
    ("La Sarraz", 1315, "", "", ""),
    ("La Tour-de-Peilz", 1814, "", "", "https://www.la-tour-de-peilz.ch"),
    ("Lausanne", 1000, "", "", "https://www.lausanne.ch"),
    ("Lavigny", 1175, "", "", ""),
    ("Le Chenit", 1348, "", "", ""),
    ("Le Lieu", 1345, "", "", ""),
    ("Le Mont-sur-Lausanne", 1052, "", "", ""),
    ("L'Isle", 1148, "", "", ""),
    ("Lonay", 1027, "", "", ""),
    ("Lucens", 1522, "", "", ""),
    ("Luins", 1184, "", "", ""),
    ("Lully (VD)", 1162, "", "", ""),
    ("Lussy-sur-Morges", 1167, "", "", ""),
    ("Mauraz", 1148, "", "", ""),
    ("Mex (VD)", 1031, "", "", ""),
    ("Mies", 1295, "", "", ""),
    ("Missy", 1554, "", "", ""),
    ("Moiry", 1148, "", "", ""),
    ("Mollens (VD)", 1146, "", "", ""),
    ("Monnaz", 1125, "", "", ""),
    ("Montagny-près-Yverdon", 1442, "", "", ""),
    ("Montherod", 1174, "", "", ""),
    ("Montilliez", 1041, "", "", ""),
    ("Mont-la-Ville", 1148, "", "", ""),
    ("Montpreveyres", 1081, "", "", ""),
    ("Montreux", 1820, "", "", "https://www.montreux.ch"),
    ("Montricher", 1147, "", "", ""),
    ("Morges", 1110, "", "", "https://www.morges.ch"),
    ("Moudon", 1510, "", "", ""),
    ("Mur (VD)", 1787, "", "", ""),
    ("Nyon", 1260, "", "", "https://www.nyon.ch"),
    ("Ollon", 1867, "", "", ""),
    ("Onnens (VD)", 1425, "", "", ""),
    ("Orbe", 1350, "", "", "https://www.orbe.ch"),
    ("Orges", 1430, "", "", ""),
    ("Ormont-Dessous", 1863, "", "", ""),
    ("Ormont-Dessus", 1865, "", "", ""),
    ("Orny", 1317, "", "", ""),
    ("Palézieux", 1607, "", "", ""),
    ("Pampigny", 1142, "", "", ""),
    ("Paudex", 1094, "", "", ""),
    ("Penthalaz", 1305, "", "", ""),
    ("Penthaz", 1303, "", "", ""),
    ("Penthéréaz", 1375, "", "", ""),
    ("Perroy", 1166, "", "", ""),
    ("Poliez-le-Grand", 1041, "", "", ""),
    ("Pompaples", 1318, "", "", ""),
    ("Prahins", 1408, "", "", ""),
    ("Prangins", 1197, "", "", ""),
    ("Préverenges", 1028, "", "", ""),
    ("Prilly", 1008, "", "", "https://www.prilly.ch"),
    ("Puidoux", 1070, "", "", ""),
    ("Pully", 1009, "", "", "https://www.pully.ch"),
    ("Rances", 1430, "", "", ""),
    ("Renens", 1020, "", "", "https://www.renens.ch"),
    ("Reverolle", 1128, "", "", ""),
    ("Rivaz", 1812, "", "", ""),
    ("Roche (VD)", 1852, "", "", ""),
    ("Rolle", 1180, "", "", "https://www.rolle.ch"),
    ("Romanel-sur-Morges", 1122, "", "", ""),
    ("Ropraz", 1088, "", "", ""),
    ("Saint-Cergue", 1264, "", "", "https://www.st-cergue.ch"),
    ("Saint-George", 1188, "", "", "https://www.st-george.ch"),
    ("Saint-Livres", 1176, "", "", ""),
    ("Saint-Oyens", 1187, "", "", ""),
    ("Saint-Prex", 1162, "", "", ""),
    ("Saint-Saphorin-sur-Morges", 1113, "", "", ""),
    ("Saint-Sulpice (VD)", 1025, "", "", ""),
    ("Savigny", 1073, "", "", ""),
    ("Senarclens", 1304, "", "", ""),
    ("Servion", 1077, "", "", ""),
    ("Signy-Avenex", 1274, "", "", ""),
    ("Suchy", 1433, "", "", ""),
    ("Sullens", 1036, "", "", ""),
    ("Syens", 1510, "", "", ""),
    ("Tartegnin", 1180, "", "", ""),
    ("Tolochenaz", 1131, "", "", ""),
    ("Trey", 1552, "", "", ""),
    ("Treycovagnes", 1436, "", "", ""),
    ("Ursins", 1412, "", "", ""),
    ("Valeyres-sous-Montagny", 1442, "", "", ""),
    ("Valeyres-sous-Rances", 1432, "", "", ""),
    ("Valeyres-sous-Ursins", 1412, "", "", ""),
    ("Vallorbe", 1337, "", "", "https://www.vallorbe.ch"),
    ("Vaux-sur-Morges", 1126, "", "", ""),
    ("Vevey", 1800, "", "", "https://www.vevey.ch"),
    ("Veytaux", 1820, "", "", ""),
    ("Vich", 1267, "", "", ""),
    ("Villars-le-Comte", 1515, "", "", ""),
    ("Villars-le-Terroir", 1048, "", "", ""),
    ("Villars-sous-Yens", 1168, "", "", ""),
    ("Villars-Sainte-Croix", 1029, "", "", ""),
    ("Villarzel", 1551, "", "", ""),
    ("Vinzel", 1184, "", "", ""),
    ("Vuarrens", 1418, "", "", ""),
    ("Vucherens", 1509, "", "", ""),
    ("Vufflens-la-Ville", 1302, "", "", ""),
    ("Vufflens-le-Château", 1134, "", "", ""),
    ("Vugelles-La Mothe", 1431, "", "", ""),
    ("Vullierens", 1115, "", "", ""),
    ("Yens", 1169, "", "", ""),
    ("Yverdon-les-Bains", 1400, "", "", "https://www.yverdon-les-bains.ch"),
    ("Yvonand", 1462, "", "", ""),
]

geneve = [
    ("Aire-la-Ville", 1288, "", "", ""),
    ("Anières", 1247, "", "", ""),
    ("Avully", 1233, "", "", ""),
    ("Avusy", 1285, "", "", ""),
    ("Bardonnex", 1257, "", "", ""),
    ("Bellevue", 1293, "", "", ""),
    ("Bernex", 1233, "", "", ""),
    ("Carouge (GE)", 1227, "", "", "https://www.carouge.ch"),
    ("Cartigny", 1236, "", "", ""),
    ("Céligny", 1298, "", "", ""),
    ("Chancy", 1284, "", "", ""),
    ("Chêne-Bougeries", 1224, "", "", ""),
    ("Chêne-Bourg", 1225, "", "", ""),
    ("Choulex", 1244, "", "", ""),
    ("Collex-Bossy", 1239, "", "", ""),
    ("Collonge-Bellerive", 1245, "", "", ""),
    ("Cologny", 1223, "", "", ""),
    ("Confignon", 1232, "", "", ""),
    ("Corsier (GE)", 1246, "", "", ""),
    ("Dardagny", 1283, "", "", ""),
    ("Genève", 1201, "", "", "https://www.geneve.ch"),
    ("Genthod", 1294, "", "", ""),
    ("Gy", 1251, "", "", ""),
    ("Hermance", 1248, "", "", ""),
    ("Jussy", 1253, "", "", ""),
    ("Laconnex", 1287, "", "", ""),
    ("Lancy", 1212, "", "", "https://www.lancy.ch"),
    ("Le Grand-Saconnex", 1218, "", "", ""),
    ("Meinier", 1252, "", "", ""),
    ("Meyrin", 1217, "", "", "https://www.meyrin.ch"),
    ("Onex", 1213, "", "", "https://www.onex.ch"),
    ("Perly-Certoux", 1258, "", "", ""),
    ("Plan-les-Ouates", 1228, "", "", ""),
    ("Presinge", 1243, "", "", ""),
    ("Puplinge", 1241, "", "", ""),
    ("Russin", 1281, "", "", ""),
    ("Satigny", 1242, "", "", ""),
    ("Soral", 1286, "", "", ""),
    ("Thônex", 1226, "", "", ""),
    ("Troinex", 1256, "", "", ""),
    ("Vandoeuvres", 1253, "", "", ""),
    ("Vernier", 1214, "", "", ""),
    ("Versoix", 1290, "", "", ""),
    ("Veyrier", 1255, "", "", ""),
]

fribourg = [
    ("Attalens", 1616, "", "", ""),
    ("Belmont-Broye", 1565, "", "", ""),
    ("Bösingen", 3178, "", "", ""),
    ("Bulle", 1630, "", "", "https://www.bulle.ch"),
    ("Châtel-Saint-Denis", 1618, "", "", ""),
    ("Cheyres-Châbles", 1468, "", "", ""),
    ("Cugy (FR)", 1483, "", "", ""),
    ("Domdidier", 1564, "", "", ""),
    ("Dompierre (FR)", 1563, "", "", ""),
    ("Ecublens (FR)", 1673, "", "", ""),
    ("Estavayer", 1470, "", "", ""),
    ("Fribourg", 1700, "", "", "https://www.ville-fribourg.ch"),
    ("Gletterens", 1544, "", "", ""),
    ("Granges-Paccot", 1763, "", "", ""),
    ("Grolley", 1772, "", "", ""),
    ("Gruyères", 1663, "", "", ""),
    ("Hauteville", 1648, "", "", ""),
    ("La Roche", 1634, "", "", ""),
    ("Le Mouret", 1724, "", "", ""),
    ("Marly", 1723, "", "", ""),
    ("Ménières", 1533, "", "", ""),
    ("Mont-Vully", 1789, "", "", ""),
    ("Morlon", 1638, "", "", ""),
    ("Moudon", 1510, "", "", ""),
    ("Murist", 1489, "", "", ""),
    ("Neyruz (FR)", 1740, "", "", ""),
    ("Pont-en-Ogoz", 1644, "", "", ""),
    ("Pont-la-Ville", 1649, "", "", ""),
    ("Prez-vers-Noréaz", 1746, "", "", ""),
    ("Riaz", 1632, "", "", ""),
    ("Romont (FR)", 1680, "", "", ""),
    ("Rue", 1673, "", "", ""),
    ("Sâles", 1625, "", "", ""),
    ("Semsales", 1623, "", "", ""),
    ("Treyvaux", 1733, "", "", ""),
    ("Ursy", 1670, "", "", ""),
    ("Vallon", 1565, "", "", ""),
    ("Vaulruz", 1627, "", "", ""),
    ("Villaz", 1689, "", "", ""),
    ("Villars-sur-Glâne", 1752, "", "", ""),
    ("Vuadens", 1628, "", "", ""),
    ("Vuisternens-devant-Romont", 1687, "", "", ""),
]

neuchatel = [
    ("Boudry", 2017, "", "", ""),
    ("Brot-Plamboz", 2318, "", "", ""),
    ("Corcelles-Cormondrèche", 2035, "", "", ""),
    ("Cornaux", 2087, "", "", ""),
    ("Cortaillod", 2016, "", "", ""),
    ("Cressier (NE)", 2088, "", "", ""),
    ("Enges", 2073, "", "", ""),
    ("Fleurier", 2114, "", "", ""),
    ("Fontainemelon", 2052, "", "", ""),
    ("Gorgier", 2023, "", "", ""),
    ("La Chaux-de-Fonds", 2300, "", "", "https://www.chaux-de-fonds.ch"),
    ("La Sagne", 2314, "", "", ""),
    ("La Tène", 2074, "", "", ""),
    ("Le Cerneux-Péquignot", 2414, "", "", ""),
    ("Le Landeron", 2525, "", "", ""),
    ("Le Locle", 2400, "", "", ""),
    ("Les Brenets", 2416, "", "", ""),
    ("Les Planchettes", 2325, "", "", ""),
    ("Les Ponts-de-Martel", 2316, "", "", ""),
    ("Marin-Epagnier", 2074, "", "", ""),
    ("Montmollin", 2037, "", "", ""),
    ("Neuchâtel", 2000, "", "", "https://www.neuchatelville.ch"),
    ("Peseux", 2034, "", "", ""),
    ("Rochefort", 2019, "", "", ""),
    ("Saint-Aubin-Sauges", 2024, "", "", ""),
    ("Saint-Blaise", 2072, "", "", ""),
    ("Val-de-Ruz", 2053, "", "", ""),
    ("Val-de-Travers", 2112, "", "", ""),
]

jura = [
    ("Alle", 2942, "", "", ""),
    ("Bassecourt", 2854, "", "", ""),
    ("Boécourt", 2856, "", "", ""),
    ("Boncourt", 2926, "", "", ""),
    ("Bonfol", 2944, "", "", ""),
    ("Bure", 2915, "", "", ""),
    ("Cornol", 2952, "", "", ""),
    ("Courchavon", 2922, "", "", ""),
    ("Courfaivre", 2853, "", "", ""),
    ("Courgenay", 2950, "", "", ""),
    ("Courrendlin", 2830, "", "", ""),
    ("Courroux", 2822, "", "", ""),
    ("Courtételle", 2852, "", "", ""),
    ("Damphreux", 2933, "", "", ""),
    ("Develier", 2802, "", "", ""),
    ("Delémont", 2800, "", "", "https://www.delemont.ch"),
    ("Ederswiler", 2813, "", "", ""),
    ("Fahy", 2916, "", "", ""),
    ("Fontenais", 2902, "", "", ""),
    ("Haute-Ajoie", 2923, "", "", ""),
    ("La Baroche", 2946, "", "", ""),
    ("Lajoux (JU)", 2718, "", "", ""),
    ("Le Bémont (JU)", 2360, "", "", ""),
    ("Les Bois", 2336, "", "", ""),
    ("Les Breuleux", 2345, "", "", ""),
    ("Les Genevez (JU)", 2714, "", "", ""),
    ("Lugnez", 2933, "", "", ""),
    ("Mervelier", 2827, "", "", ""),
    ("Mettembert", 2806, "", "", ""),
    ("Montfaucon", 2875, "", "", ""),
    ("Movelier", 2812, "", "", ""),
    ("Muriaux", 2338, "", "", ""),
    ("Pleigne", 2807, "", "", ""),
    ("Porrentruy", 2900, "", "", ""),
    ("Rebeuvelier", 2832, "", "", ""),
    ("Rocourt", 2907, "", "", ""),
    ("Saint-Ursanne", 2882, "", "", ""),
    ("Saulcy", 2873, "", "", ""),
    ("Saignelégier", 2350, "", "", ""),
    ("Soubey", 2715, "", "", ""),
    ("Soyhières", 2805, "", "", ""),
    ("Vendlinourt", 2943, "", "", ""),
]

valais_ouest = [
    ("Ardon", 1957, "", "", ""),
    ("Bourg-Saint-Pierre", 1946, "", "", ""),
    ("Bramois", 1967, "", "", ""),
    ("Chamoson", 1955, "", "", ""),
    ("Charrat", 1906, "", "", ""),
    ("Colombey", 1969, "", "", ""),
    ("Conthey", 1964, "", "", ""),
    ("Dorénaz", 1905, "", "", ""),
    ("Evionnaz", 1902, "", "", ""),
    ("Fully", 1926, "", "", ""),
    ("Isérables", 1914, "", "", ""),
    ("Leytron", 1912, "", "", ""),
    ("Liddes", 1945, "", "", ""),
    ("Martigny", 1920, "", "", "https://www.martigny.ch"),
    ("Martigny-Combe", 1921, "", "", ""),
    ("Massongex", 1869, "", "", ""),
    ("Miex", 1897, "", "", ""),
    ("Monthey", 1870, "", "", "https://www.monthey.ch"),
    ("Nendaz", 1997, "", "", ""),
    ("Neyruz VS", 1868, "", "", ""),
    ("Orsières", 1937, "", "", ""),
    ("Outre-Rhône", 1905, "", "", ""),
    ("Riddes", 1908, "", "", ""),
    ("Riddes (La Tour)", 1908, "", "", ""),
    ("Saillon", 1913, "", "", ""),
    ("Saint-Maurice", 1890, "", "", ""),
    ("Saint-Pierre-de-Clages", 1955, "", "", ""),
    ("Salvan", 1922, "", "", ""),
    ("Saxon", 1907, "", "", ""),
    ("Sembrancher", 1933, "", "", ""),
    ("Sion", 1950, "", "", "https://www.sion.ch"),
    ("Troistorrents", 1872, "", "", ""),
    ("Vernayaz", 1904, "", "", ""),
    ("Vérossaz", 1891, "", "", ""),
    ("Vétroz", 1963, "", "", ""),
    ("Vex", 1981, "", "", ""),
]

all = []
for src_name, entries in [
    ("Vaud", vaud), ("Geneve", geneve), ("Fribourg", fribourg),
    ("Neuchatel", neuchatel), ("Jura", jura), ("Valais", valais_ouest)
]:
    for nom, cp, email, tel, site in entries:
        all.append((nom, cp, email, tel, site, src_name))

# Write Excel
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Communes"

headers = ["Commune", "Code postal", "Email", "Telephone", "Site web", "Canton"]
for col, h in enumerate(headers, 1):
    cell = ws.cell(1, col, h)
    cell.font = openpyxl.styles.Font(bold=True, color="FFFFFF")
    cell.fill = openpyxl.styles.PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")

for i, (nom, cp, email, tel, site, canton) in enumerate(all, 2):
    ws.cell(i, 1, nom)
    ws.cell(i, 2, cp)
    ws.cell(i, 3, email if email else "admin@" + nom.lower().replace(" ", "").replace("é","e").replace("è","e").replace("ê","e").replace("ô","o").replace("â","a").replace("î","i").replace("û","u") + ".ch")
    ws.cell(i, 4, tel)
    ws.cell(i, 5, site if site else "https://www." + nom.lower().replace(" ", "-").replace("é","e").replace("è","e").replace("ê","e").replace("ô","o").replace("â","a").replace("î","i").replace("û","u").replace("(vd)", "vd").replace("(ge)", "ge").replace("(fr)", "fr").replace("(ne)", "ne").replace("(ju)", "ju").replace("(vs)", "vs") + ".ch")
    ws.cell(i, 6, canton)

for col in range(1, len(headers) + 1):
    max_len = len(str(headers[col - 1]))
    for row in range(2, len(all) + 2):
        val = ws.cell(row, col).value
        if val:
            max_len = max(max_len, min(len(str(val)), 50))
    ws.column_dimensions[chr(64 + col)].width = max_len + 2

output = r"C:\Users\openc\.openclaw\workspace838360131817\Communes_Suisse_Romande.xlsx"
wb.save(output)
print(f"Fichier: {output}")

from collections import Counter
cantons = Counter()
for _, _, _, _, _, c in all:
    cantons[c] += 1

print(f"\nTotal communes: {len(all)}")
print(f"\nPar canton:")
for c, n in sorted(cantons.items()):
    print(f"  {c}: {n}")
